import { loadConfigAsync } from '../config/config.js';
import { searchRepos, type SearchResult } from '../search/query.js';
import { streamLLM, isLLMError } from '../gemini/llm.js';

/**
 * Options for repository recommendations.
 */
export interface RecommendOptions {
  /** The natural language query describing what the user is looking for */
  query: string;
  /** Number of final recommendations to return (default: 3) */
  limit: number;
  /** Optional filters to apply to candidate search */
  filters?: {
    /** Filter by programming language */
    language?: string;
    /** Filter to starred repos only */
    starred?: boolean;
    /** Filter to owned repos only */
    owned?: boolean;
    /** Filter by repo owner username */
    owner?: string;
  };
}

/**
 * A single repository recommendation with LLM-generated reasoning.
 */
export interface Recommendation {
  /** Rank of this recommendation (1-based) */
  rank: number;
  /** Full name of the repository (owner/repo) */
  repoFullName: string;
  /** URL to the repository on GitHub */
  htmlUrl: string;
  /** LLM-generated explanation of why this repo is relevant */
  reasoning: string;
}

/**
 * Result of a recommendation query.
 */
export interface RecommendResult {
  /** Array of recommendations, ordered by rank */
  recommendations: Recommendation[];
  /** The original query */
  query: string;
  /** Number of repos passed to LLM as context */
  candidatesConsidered: number;
  /** Number of input tokens used by the LLM */
  inputTokens: number;
  /** Number of output tokens generated by the LLM */
  outputTokens: number;
  /** Total duration including search + LLM call in milliseconds */
  durationMs: number;
  /** Error message if any stage failed */
  error?: string;
}

/**
 * Raw recommendation item from LLM JSON response.
 */
interface RawRecommendation {
  rank?: number;
  repoFullName?: string;
  htmlUrl?: string;
  reasoning?: string;
}

/**
 * System prompt for the recommendation LLM.
 */
const SYSTEM_PROMPT = `You are a developer tool assistant. Your job is to recommend the most relevant GitHub repositories from a provided list based on the user's query. You must respond with valid JSON only — no markdown, no explanation outside the JSON.`;

/**
 * Build the user prompt for repository recommendations.
 *
 * @param query - The user's query
 * @param candidates - Search results to include as candidates
 * @param limit - Number of recommendations to request
 * @returns The formatted prompt string
 */
export function buildRecommendPrompt(
  query: string,
  candidates: SearchResult[],
  limit: number
): string {
  // Format each candidate
  const candidateLines = candidates.map((c) => {
    const description = c.description ?? 'No description';
    const language = c.language ?? 'Unknown language';
    return `- ${c.repoFullName}: ${description} (${language}) — ${c.htmlUrl}`;
  });

  const candidatesText = candidateLines.join('\n');

  return `Query: ${query}

Here are the candidate repositories:
${candidatesText}

Based on the query, recommend the top ${limit} most relevant repositories.

Respond with a JSON array of objects in this exact format:
[
  {
    "rank": 1,
    "repoFullName": "owner/repo",
    "htmlUrl": "https://github.com/owner/repo",
    "reasoning": "One or two sentences explaining why this repo is relevant to the query."
  }
]

Only include repositories from the provided list. Do not invent repositories.
Rank by relevance to the query. Be concise in reasoning.`;
}

/**
 * Strip markdown code fences or non-JSON preamble from a string.
 *
 * LLMs often wrap JSON in markdown code blocks even when instructed not to,
 * or add introductory/concluding text before/after the JSON block.
 *
 * @param text - The text to clean
 * @returns Text with only the JSON content
 */
function stripCodeFences(text: string): string {
  let cleaned = text.trim();

  // Strategy 1: Look for content inside ```json ... ``` or ``` ... ``` blocks
  const codeBlockMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (codeBlockMatch && codeBlockMatch[1]) {
    return codeBlockMatch[1].trim();
  }

  // Strategy 2: Look for the first '[' and last ']' if we expect an array
  const startArray = cleaned.indexOf('[');
  const endArray = cleaned.lastIndexOf(']');
  if (startArray !== -1 && endArray !== -1 && endArray > startArray) {
    return cleaned.slice(startArray, endArray + 1).trim();
  }

  // Strategy 3: Look for the first '{' and last '}' if it returned a single object
  const startObj = cleaned.indexOf('{');
  const endObj = cleaned.lastIndexOf('}');
  if (startObj !== -1 && endObj !== -1 && endObj > startObj) {
    return cleaned.slice(startObj, endObj + 1).trim();
  }

  // Fallback to original trimming logic if no markers found
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.slice(7);
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.slice(3);
  }

  if (cleaned.endsWith('```')) {
    cleaned = cleaned.slice(0, -3);
  }

  return cleaned.trim();
}

/**
 * Parse and validate recommendations from LLM response.
 *
 * @param text - The raw LLM response text
 * @param limit - Maximum number of recommendations to return
 * @returns Array of valid recommendations
 */
function parseRecommendations(text: string, limit: number): Recommendation[] {
  try {
    const cleaned = stripCodeFences(text);
    let parsed = JSON.parse(cleaned);

    // If LLM returned a single object instead of an array, wrap it
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      parsed = [parsed];
    }

    if (!Array.isArray(parsed)) {
      return [];
    }

    const recommendations: Recommendation[] = [];

    for (const item of parsed) {
      // Validate required fields (more lenient type checking)
      if (
        item.repoFullName &&
        typeof item.repoFullName === 'string' &&
        item.htmlUrl &&
        typeof item.htmlUrl === 'string' &&
        item.reasoning &&
        typeof item.reasoning === 'string'
      ) {
        recommendations.push({
          rank: typeof item.rank === 'number' ? item.rank : recommendations.length + 1,
          repoFullName: item.repoFullName,
          htmlUrl: item.htmlUrl,
          reasoning: item.reasoning,
        });
      }

      // Stop if we have enough
      if (recommendations.length >= limit) {
        break;
      }
    }

    return recommendations;
  } catch {
    // JSON parsing failed
    return [];
  }
}

/**
 * Create an empty recommendation result.
 *
 * @param query - The original query
 * @param candidatesConsidered - Number of candidates that were considered
 * @param durationMs - Duration of the operation
 * @returns An empty RecommendResult
 */
function emptyResult(
  query: string,
  candidatesConsidered: number = 0,
  durationMs: number = 0,
  error?: string
): RecommendResult {
  return {
    recommendations: [],
    query,
    candidatesConsidered,
    inputTokens: 0,
    outputTokens: 0,
    durationMs,
    error,
  };
}

/**
 * Get AI-powered repository recommendations for a query.
 *
 * This function:
 * 1. Runs vector search to find candidate repositories
 * 2. Builds a prompt with the candidates
 * 3. Calls the Gemini LLM to rank and explain recommendations
 * 4. Parses and validates the LLM response
 *
 * Never throws - returns an empty result on any error.
 *
 * @param options - Recommendation options
 * @returns RecommendResult with ranked recommendations
 */
export async function recommendRepos(
  options: RecommendOptions
): Promise<RecommendResult> {
  const startTime = performance.now();
  const { query, limit, filters } = options;

  try {
    // Load config to get API key
    const config = await loadConfigAsync();
    if (!config.geminiKey) {
      return emptyResult(query, 0, performance.now() - startTime);
    }

    // Step 1: Search for candidates (over-fetch to give LLM more context)
    const candidateLimit = limit * 5;
    const searchResult = await searchRepos(query, {
      limit: candidateLimit,
      language: filters?.language,
      starred: filters?.starred,
      owned: filters?.owned,
      owner: filters?.owner,
    });

    const candidates = searchResult.results;

    // If no candidates, return empty result
    if (candidates.length === 0) {
      return emptyResult(query, 0, performance.now() - startTime);
    }

    // Step 2: Build the prompt
    const prompt = buildRecommendPrompt(query, candidates, limit);

    // Step 3: Call the LLM
    const llmResult = await streamLLM(config.geminiKey, prompt, SYSTEM_PROMPT);

    const durationMs = performance.now() - startTime;

    // Step 4: Handle LLM error
    if (isLLMError(llmResult)) {
      return emptyResult(query, candidates.length, durationMs, llmResult.error);
    }

    // Step 5: Parse recommendations
    const recommendations = parseRecommendations(llmResult.text, limit);

    if (recommendations.length === 0 && llmResult.text) {
      return emptyResult(
        query,
        candidates.length,
        durationMs,
        'Failed to parse LLM response as valid recommendations'
      );
    }

    return {
      recommendations,
      query,
      candidatesConsidered: candidates.length,
      inputTokens: llmResult.inputTokens,
      outputTokens: llmResult.outputTokens,
      durationMs,
    };
  } catch (err) {
    // Never throw - return empty result
    const errorMessage = err instanceof Error ? err.message : 'Unknown recommendation error';
    return emptyResult(query, 0, performance.now() - startTime, errorMessage);
  }
}
